//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MsEmployee()
        {
            this.TrHeaders = new HashSet<TrHeader>();
        }
    
        public System.Guid EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> EmployeeDOB { get; set; }
        public string EmployeeGender { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeePhone { get; set; }
        public string EmployeeEmail { get; set; }
        public Nullable<decimal> EmployeeSalary { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrHeader> TrHeaders { get; set; }
    }
}
