//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrDetail
    {
        public System.Guid DetailID { get; set; }
        public Nullable<System.Guid> TransactionID { get; set; }
        public Nullable<System.Guid> FlowerID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
    
        public virtual MsFlower MsFlower { get; set; }
        public virtual TrHeader TrHeader { get; set; }
    }
}
